# Steve-head minecraft
import turtle

# Setup
turtle.penup()
turtle.forward(400)
turtle.pendown()
# start

# Head
turtle.fillcolor('#ad816d') 
turtle.pencolor('#ad816d')
turtle.begin_fill() 
turtle.right(90)
turtle.forward(400)
turtle.right(90)
turtle.forward(800)
turtle.right(90)
turtle.forward(800)
turtle.right(90)
turtle.forward(800)
turtle.right(90)
turtle.forward(400)
turtle.end_fill()


# Pre-hair
turtle.penup()
turtle.right(180)
turtle.forward(100)
turtle.left(90)
turtle.pendown()

# Fill-hair
turtle.fillcolor('#291E0B')
turtle.pencolor('#291E0B')
turtle.begin_fill()
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(600)
turtle.left(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(300)
turtle.right(90)
turtle.forward(800)
turtle.right(90)
turtle.forward(300)
turtle.end_fill()

# Pre-right_eye
turtle.penup()
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.pendown()

# Right-eye
turtle.fillcolor('white')
turtle.pencolor('white')
turtle.begin_fill()
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.end_fill()

turtle.penup()
turtle.left(90)
turtle.forward(100)
turtle.pendown()
turtle.fillcolor('#2622AE')
turtle.pencolor('#2622AE')
turtle.begin_fill()
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.end_fill()

# Pre-left_eye
turtle.penup()
turtle.left(90)
turtle.forward(300)
turtle.pendown()

# Left-eye
turtle.fillcolor('#2622AE')
turtle.pencolor('#2622AE')
turtle.begin_fill()
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.end_fill()

turtle.penup()
turtle.left(90)
turtle.forward(100)
turtle.pendown()
turtle.fillcolor('white')
turtle.pencolor('white')
turtle.begin_fill()
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.end_fill()

# Pre-nose
turtle.penup()
turtle.right(180)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.pendown()

# Nose
turtle.fillcolor('#6A3F30')
turtle.pencolor('#6A3F30')
turtle.begin_fill()
turtle.forward(200)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(100)
turtle.end_fill()

# Pre-mouth
turtle.penup()
turtle.right(180)
turtle.forward(100)
turtle.pendown()

# Mouth
turtle.fillcolor('#8A4C3F')
turtle.pencolor('#8A4C3F')
turtle.begin_fill()
turtle.left(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(100)
turtle.end_fill()


# Beard
turtle.left(90)
turtle.fillcolor('#46230F')
turtle.pencolor('#46230F')
turtle.begin_fill()
turtle.forward(100)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(400)
turtle.left(90)
turtle.forward(200)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(100)
turtle.end_fill()

# Pre-blush
# end   
turtle.mainloop()